Relax check on google photos takeout
RhetTbull/osxphotos pull request #1348
Opened 2023-12-26 23:12 UTC by LunarLanding

Found that sidecar files from google takeout not always have the 'googlePhotosOrigin' field.
So I disabled the check. Maybe that's good enough?

2023-12-27 04:03 UTC, RhetTbull requested changes
Thanks. I had a limited Google takeout set to work with. Rather than remove the check entirely I'd rather check several keys to verify at least one is present. Can you take a look at `metadata_from_google_takeout()` in the same file and check to see if any of title, description, geoData, etc is present? That should be more robust in case an unknown JSON file is found.

2023-12-27 04:04 UTC, RhetTbull commented
@all-contributors please add @LunarLanding for code

2023-12-27 13:31 UTC, LunarLanding commented
All of the keys were present, so by default it checks as before for googlePhotosOrigin, and in case that fails, it checks for all the keys that were listed in the docs. This should strictly improve things and fixes the issue I had.

2023-12-29 05:15 UTC, RhetTbull approved these changes

2023-12-29 05:15 UTC, merged